name: Android Build Verification

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v7

    - name: Set up JDK 21 (Latest Actions v6)
      uses: actions/setup-java@v6
      with:
        java-version: 'latest'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle (Latest Actions v6) 
      uses: gradle/actions/setup-gradle@v6

    - name: Run Build Test
      run: chmod +x gradlew && ./gradlew assembleDebug --stacktrace
